### ISSUE TITLE
Pipe to notification center

### ISSUE THREAD

**Issue by bebraw** [leonidas/james.js#15]
Hi,

It would be awesome if it was possible to pipe the output to notification center. This would allow me to see instantly when something fails without having to check out the terminal in which _james_ is running. This is the way [node-dev](https://npmjs.org/package/node-dev) package works.

Given I have growl installed I tried `james | growlnotify`. Unfortunately nothing happens. Regular `console.log` pipes alright. Note that my default build is in `watch` mode so I guess that chomps the output somehow even though it seems to use `console.log`.

It outputs just fine using some other build option as long as _watch_  is not used. In this case, however, the output contains some extra characters caused by coloring. _growlnotify_ does not interpret the symbols and just shows them instead.

I think this means we should at least do the following things:
- [x] Investigate why _watch_ doesn't work properly
- [x] Allow output colors to be disabled for _james_ (separate issue?). That way we are compatible with notifications (do they support color even in theory?)
- [ ] (optional) Implement custom sink that supports both Growl and Notification Center (and possibly supports color if that is possible)

Based on what you think I could probably tackle the last one and possibly the second.

**Comment by jkeskikangas** [comment]
1. I'm investigating ATM. `console.log` seems to work on my machine, error redirection not.
2. Could be done by checking whether the output is TTY: http://nodejs.org/api/tty.html#tty_tty
3. Sounds great and should be quite easy to do. There's only a few places where james is producing output.

**Comment by jkeskikangas** [comment]
hmh. Error redirects seem to work, too:

```
james watch &> asdf.txt &
tail -f asdf.txt
```

Outputs

```
Wrote file public/js/bundle.js
ERROR: unmatched OUTDENT
Loading Jamesfile
Executing task "watch"
Wrote file public/js/bundle.js
```

Perhaps growl can't handle coloring. I'll add checks whether the output is TTY or not.

**Comment by jkeskikangas** [comment]
Done with 1. and 2.

I'd propose implementing 3. as a post processor for james, e.g.,

```
$ james watch | james-growl
```

I'd guess that's easier to implement than a, e.g., plugin architecture.

Error messages starts with `Error:`, warnings with `Warn:` and the rest are info messages. Feel free to implement as fit for your usage.

**Comment by bebraw** [comment]
I solved 3. with a [little hack](https://gist.github.com/bebraw/5841036). It wraps [terminal-notifier](https://github.com/alloy/terminal-notifier) and seems to work ok.

I did notice info messages still contained some of that coloring syntax in the messages even after the latest changes. If you have access to an OS X system, give the aforementioned hack a go to see whether you can confirm it.

I'm closing this issue as we seem to have covered it quite well.
