### ISSUE TITLE
Throttle watches

### ISSUE THREAD

**Issue by japsu** [leonidas/james.js#17]
Suppose I am watching a bunch of files and cause multiple files to be changed at the same time by eg. `git checkout another-branch`.

Each of these files being changed by `git checkout` now triggers the watch, starting multiple rebuilds.

Better yet, at least when using `browserify`, they all write to the same file, producing a broken result.

This could be fixed by eg. _.debounce: wait for eg. 500 milliseconds, collecting tasks that need to be run, and running each task only once.

**Comment by jkeskikangas** [comment]
500ms sounds like a lot, maybe 50-100ms could do it while not disturbing the development workflow. Also https://github.com/substack/watchify could help (at least with build times).

**Comment by jkeskikangas** [comment]
Easiest way to implement this (may or may not be the correct one), would be to debounce callbacks in Jamesfile. I'd be a bit hesitant to delay events in the internals of James, as it would affect on all users and all watch tasks.
